# needs at least docker-compose 1.18.0 (1.10.0 for sysctls option and 1.18.0 for custom network name)
version: "2.1"
 
services:

  vpn-client:
    image: vpn-client:$VERSION_VPN_CLIENT
    build: "https://git.scimetis.net/yohan/docker-VPN-client.git"
    restart: always
    volumes:
      - ./keys:/etc/openvpn/client:Z
      - ./client.conf:/etc/openvpn/openvpn.conf:Z
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.ip_forward: 1
    devices:
      - "/dev/net/tun:/dev/net/tun"
    dns: 80.67.169.12
    networks:
      openvpn-network:
        ipv4_address: 172.31.1.2

networks:
  openvpn-network:
    name: openvpn-network
    ipam:
      config:
        - subnet: 172.31.1.0/24

